Repository mandiant/VM-Packages, pull requests merged in 2022-05, with the labels that each got.

#42 Upload Chocolatey logs in daily run
  .github/workflows/daily.yml
Labels: :gem: enhancement

#40 Add Issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/new_package.yml
Labels: :gem: enhancement

#50 Send automatic PR from issue template 🚀
  .github/ISSUE_TEMPLATE/new_package.yml
  .github/workflows/new_package.yml
  scripts/utils/create_package_template.py
  scripts/utils/create_package_template_from_json.py
Labels: :gem: enhancement, :runner: CI

#55 :robot: Add regshot.vm
  packages/regshot.vm/regshot.vm.nuspec
  packages/regshot.vm/tools/chocolateyinstall.ps1
  packages/regshot.vm/tools/chocolateyuninstall.ps1
Labels: :new: package
