Repository mandiant/VM-Packages, pull requests merged in 2022-11, with the labels that each got.

#98 Update dependencies automatically
  .github/workflows/update_package.yml
  packages/notepadplusplus.vm/notepadplusplus.vm.nuspec
  packages/notepadplusplus.vm/tools/chocolateyinstall.ps1
  scripts/utils/update_package.py
Labels: :gem: enhancement, :runner: CI

#104 Test all packages in daily
  .github/workflows/daily.yml
  scripts/test/test_install.ps1
Labels: :gem: enhancement, :runner: CI

#117 Display Failures in daily run
  .github/workflows/daily.yml
Labels: :runner: CI

#129 Fix renamed packages not being pushed
  .github/workflows/ci.yml
Labels: :bug: bug
