Repository mandiant/VM-Packages, pull requests merged in 2023-10, with the labels that each got.

#681 Use os.path.join in lint.py
  scripts/test/lint.py
Labels: :bug: bug, :runner: CI

#679 Add sfextract.vm
  packages/sfextract.vm/sfextract.vm.nuspec
  packages/sfextract.vm/tools/chocolateyinstall.ps1
  packages/sfextract.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#682 :robot: Add reg_export.vm
  packages/reg_export.vm/reg_export.vm.nuspec
  packages/reg_export.vm/tools/chocolateyinstall.ps1
  packages/reg_export.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#680 Merge Java and Android categories
  .github/ISSUE_TEMPLATE/new_metapackage.yml
  .github/ISSUE_TEMPLATE/new_package.yml
  categories.txt
  packages/apktool.vm/apktool.vm.nuspec
  packages/apktool.vm/tools/chocolateyinstall.ps1
  packages/apktool.vm/tools/chocolateyuninstall.ps1
  packages/bytecodeviewer.vm/bytecodeviewer.vm.nuspec
  packages/bytecodeviewer.vm/tools/chocolateyinstall.ps1
  packages/bytecodeviewer.vm/tools/chocolateyuninstall.ps1
  packages/dex2jar.vm/dex2jar.vm.nuspec
  packages/dex2jar.vm/tools/chocolateyinstall.ps1
  packages/dex2jar.vm/tools/chocolateyuninstall.ps1
  scripts/test/lint.py
Labels: :gem: enhancement, :cyclone: FLARE-VM

#683 Installer improvements
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM, :cyclone: COMMANDO-VM

#697 installer.vm: fix bug by adding System.Drawing
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#689 More improvements in installer.vm
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM, :cyclone: COMMANDO-VM

#704 installer.vm: Fix bug with background
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#700 Add the ImHex.vm package
  packages/imhex.vm/imhex.vm.nuspec
  packages/imhex.vm/tools/chocolateyinstall.ps1
  packages/imhex.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#712 vcbuildtools.vm: Stop updating dependency
  packages/vcbuildtools.vm/vcbuildtools.vm.nuspec
Labels: :gem: enhancement, :cyclone: FLARE-VM

#714 Improve documentation
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  README.md
Labels: :page_facing_up: documentation

#350 :robot: Add psnotify.vm
  packages/psnotify.vm/psnotify.vm.nuspec
  packages/psnotify.vm/tools/chocolateyinstall.ps1
  packages/psnotify.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#349 :robot: Add garbageman.vm
  packages/garbageman.vm/garbageman.vm.nuspec
  packages/garbageman.vm/tools/chocolateyinstall.ps1
  packages/garbageman.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#715 installer.vm: Log fixes
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#721 category: Rename 'Android/Java' to fix bug
  .github/ISSUE_TEMPLATE/new_metapackage.yml
  .github/ISSUE_TEMPLATE/new_package.yml
  categories.txt
  packages/apktool.vm/apktool.vm.nuspec
  packages/apktool.vm/tools/chocolateyinstall.ps1
  packages/apktool.vm/tools/chocolateyuninstall.ps1
  packages/bytecodeviewer.vm/bytecodeviewer.vm.nuspec
  packages/bytecodeviewer.vm/tools/chocolateyinstall.ps1
  packages/bytecodeviewer.vm/tools/chocolateyuninstall.ps1
  packages/dex2jar.vm/dex2jar.vm.nuspec
  packages/dex2jar.vm/tools/chocolateyinstall.ps1
  packages/dex2jar.vm/tools/chocolateyuninstall.ps1
Labels: :bug: bug

#720 Add openjdk.vm
  packages/bytecodeviewer.vm/bytecodeviewer.vm.nuspec
  packages/dex2jar.vm/dex2jar.vm.nuspec
  packages/ghidra.vm/ghidra.vm.nuspec
  packages/openjdk.vm/openjdk.vm.nuspec
  packages/openjdk.vm/tools/chocolateyinstall.ps1
  scripts/test/lint.py
Labels: :gem: enhancement, :new: package, :cyclone: FLARE-VM

#705 :robot: Add rpcview.vm
  packages/rpcview.vm/rpcview.vm.nuspec
  packages/rpcview.vm/tools/chocolateyinstall.ps1
  packages/rpcview.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#726 pkg-unpacker.vm: Prevent npm warn to fail package
  packages/pkg-unpacker.vm/pkg-unpacker.vm.nuspec
  packages/pkg-unpacker.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#703 Ignore success_failure.json
  .gitignore
Labels: :gem: enhancement
