Repository mandiant/VM-Packages, pull requests merged in 2023-11, with the labels that each got.

#723 Issue template: Add dependencies to new package
  .github/ISSUE_TEMPLATE/new_package.yml
Labels: :page_facing_up: documentation, :gem: enhancement

#727 Improve zip download code
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM, :cyclone: COMMANDO-VM

#736 :robot: Add netcat.vm
  packages/netcat.vm/netcat.vm.nuspec
  packages/netcat.vm/tools/chocolateyinstall.ps1
  packages/netcat.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#743 Issue template: improve bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: :page_facing_up: documentation, :runner: CI

#744 Issue template: Fix bug template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: :bug: bug

#745 debloat: Disable Microsoft Connectivity Test
  packages/debloat.vm/debloat.vm.nuspec
  packages/debloat.vm/tools/win10.xml
Labels: :gem: enhancement

#751 Improve files deleted in VM-Remove-DesktopFiles/VM-Clean-Up
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement
