Repository mandiant/VM-Packages, pull requests merged in 2023-04, with the labels that each got.

#280 Create telnet package
  packages/telnet.vm/telnet.vm.nuspec
  packages/telnet.vm/tools/chocolateyinstall.ps1
  packages/telnet.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#274 Add Teamfiltration
  packages/teamfiltration.vm/teamfiltration.vm.nuspec
  packages/teamfiltration.vm/tools/chocolateyinstall.ps1
  packages/teamfiltration.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#295 Improve package updates automation
  .github/workflows/update_package.yml
  scripts/test/test_install.ps1
  scripts/utils/update_package.py
Labels: :bug: bug, :runner: CI

#291 Lint categories
  categories.txt
  packages/cmder.vm/cmder.vm.nuspec
  packages/cmder.vm/tools/chocolateyinstall.ps1
  packages/cmder.vm/tools/chocolateyuninstall.ps1
  packages/cyberchef.vm/cyberchef.vm.nuspec
  packages/cyberchef.vm/tools/chocolateyinstall.ps1
  packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
  packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
  packages/idafree.vm/idafree.vm.nuspec
  packages/idafree.vm/tools/chocolateyinstall.ps1
  packages/nmap.vm/nmap.vm.nuspec
  packages/nmap.vm/tools/chocolateyinstall.ps1
  packages/ollydbg.vm/ollydbg.vm.nuspec
  packages/ollydbg.vm/tools/chocolateyinstall.ps1
  packages/ollydbg.vm/tools/chocolateyuninstall.ps1
  packages/ollydbg2.vm/ollydbg2.vm.nuspec
  packages/ollydbg2.vm/tools/chocolateyinstall.ps1
  packages/ollydbg2.vm/tools/chocolateyuninstall.ps1
  packages/vcbuildtools.vm/tools/chocolateyinstall.ps1
  packages/vcbuildtools.vm/tools/chocolateyuninstall.ps1
  packages/vcbuildtools.vm/vcbuildtools.vm.nuspec
  packages/x64dbg.vm/tools/chocolateyinstall.ps1
  packages/x64dbg.vm/tools/chocolateyuninstall.ps1
  packages/x64dbg.vm/x64dbg.vm.nuspec
  scripts/test/lint.py
  scripts/utils/create_package_template.py
Labels: :runner: CI

#300 Replace success/failure badges by failures file
  .github/workflows/daily.yml
  README.md
  scripts/test/test_install.ps1
  scripts/utils/generate_daily_results.py
Labels: :gem: enhancement, :runner: CI

#302 Unify way of displaying errors in GH actions
  .github/actions/upload-logs/action.yml
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  .github/workflows/update_package.yml
Labels: :gem: enhancement, :runner: CI

#316 :robot: Add shellcode_launcher.vm
  packages/shellcode_launcher.vm/shellcode_launcher.vm.nuspec
  packages/shellcode_launcher.vm/tools/chocolateyinstall.ps1
  packages/shellcode_launcher.vm/tools/chocolateyuninstall.ps1
Labels: :new: package
