Repository mandiant/VM-Packages, pull requests merged in 2024-10, with the labels that each got.

#1140 Add js-beautify.vm
  packages/js-beautify.vm/js-beautify.vm.nuspec
  packages/js-beautify.vm/tools/chocolateyinstall.ps1
  packages/js-beautify.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#1054 Update CyberChef to use CyberChef icon
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/cyberchef.vm/cyberchef.vm.nuspec
  packages/cyberchef.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1146 Support the valid return codes at googlechrome.vm
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/googlechrome.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1137 Fix Custom Taskbar from breaking on Win 11
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1143 Add ipython.vm
  packages/ipython.vm/ipython.vm.nuspec
  packages/ipython.vm/tools/chocolateyinstall.ps1
  packages/ipython.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#1148 [cyberchef] Improve CyberChef shortcut
  packages/cyberchef.vm/cyberchef.vm.nuspec
  packages/cyberchef.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM
