Repository mandiant/VM-Packages, pull requests merged in 2024-06, with the labels that each got.

#1069 Install Diaphora as an IDA plugin
  packages/ida.diaphora.vm/ida.diaphora.vm.nuspec
  packages/ida.diaphora.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.diaphora.vm/ida.plugin.diaphora.vm.nuspec
  packages/ida.plugin.diaphora.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.diaphora.vm/tools/chocolateyuninstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1070 [extreme_dumper.vm] Update broken URL
  packages/extreme_dumper.vm/extreme_dumper.vm.nuspec
  packages/extreme_dumper.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1081 [CI] Check daily that local versions match MyGet
  .github/workflows/compare_myget.yml
  README.md
  scripts/utils/compare_myget.py
Labels: :runner: CI

#1079 Increase version to push packages (2nd round)
  packages/ollydbg.plugin.scyllahide.vm/ollydbg.plugin.scyllahide.vm.nuspec
  packages/ollydbg2.plugin.ollydumpex.vm/ollydbg2.plugin.ollydumpex.vm.nuspec
  packages/ollydbg2.plugin.scyllahide.vm/ollydbg2.plugin.scyllahide.vm.nuspec
  packages/systeminformer.vm/systeminformer.vm.nuspec
  packages/testdisk.vm/testdisk.vm.nuspec
  packages/winscp.vm/winscp.vm.nuspec
  packages/x64dbg.plugin.ollydumpex.vm/x64dbg.plugin.ollydumpex.vm.nuspec
  packages/x64dbg.vm/x64dbg.vm.nuspec
Labels: :bug: bug, :runner: CI

#1087 Add python and jupyter vscode extension packages
  packages/vscode.extension.jupyter.vm/tools/chocolateyinstall.ps1
  packages/vscode.extension.jupyter.vm/tools/chocolateyuninstall.ps1
  packages/vscode.extension.jupyter.vm/vscode.extension.jupyter.vm.nuspec
  packages/vscode.extension.python.vm/tools/chocolateyinstall.ps1
  packages/vscode.extension.python.vm/tools/chocolateyuninstall.ps1
  packages/vscode.extension.python.vm/vscode.extension.python.vm.nuspec
  scripts/test/lint.py
Labels: :new: package, :cyclone: FLARE-VM

#1090 :robot: Add pe_unmapper.vm
  packages/pe_unmapper.vm/pe_unmapper.vm.nuspec
  packages/pe_unmapper.vm/tools/chocolateyinstall.ps1
  packages/pe_unmapper.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#1091 Use VM-Assert-Signature to verify the metasploit MSI
  packages/metasploit.vm/metasploit.vm.nuspec
  packages/metasploit.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement

#1088 Fix the calls to VM-Uninstall-With-Uninstaller
  packages/7zip-15-05.vm/7zip-15-05.vm.nuspec
  packages/7zip-15-05.vm/tools/chocolateyuninstall.ps1
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/explorersuite.vm/explorersuite.vm.nuspec
  packages/explorersuite.vm/tools/chocolateyuninstall.ps1
  packages/metasploit.vm/metasploit.vm.nuspec
  packages/metasploit.vm/tools/chocolateyuninstall.ps1
  packages/nmap.vm/nmap.vm.nuspec
  packages/nmap.vm/tools/chocolateyuninstall.ps1
  packages/npcap.vm/npcap.vm.nuspec
  packages/npcap.vm/tools/chocolateyuninstall.ps1
  packages/vbdec.vm/tools/chocolateyuninstall.ps1
  packages/vbdec.vm/vbdec.vm.nuspec
Labels: :bug: bug

#1092 Add the Time Travel Debugging CLI package
  packages/ttd.vm/tools/chocolateyinstall.ps1
  packages/ttd.vm/tools/chocolateyuninstall.ps1
  packages/ttd.vm/ttd.vm.nuspec
Labels: :new: package, :cyclone: FLARE-VM
