Repository mandiant/VM-Packages, pull requests merged in 2024-02, with the labels that each got.

#891 :robot: Add sclauncher.vm
  packages/sclauncher.vm/sclauncher.vm.nuspec
  packages/sclauncher.vm/tools/chocolateyinstall.ps1
  packages/sclauncher.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#894 :robot: Add sclauncher64.vm
  packages/sclauncher64.vm/sclauncher64.vm.nuspec
  packages/sclauncher64.vm/tools/chocolateyinstall.ps1
  packages/sclauncher64.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#876 :robot: Add microsoft-windows-terminal.vm
  .github/workflows/ci.yml
  packages/microsoft-windows-terminal.vm/microsoft-windows-terminal.vm.nuspec
  packages/microsoft-windows-terminal.vm/tools/chocolateyinstall.ps1
  packages/microsoft-windows-terminal.vm/tools/chocolateyuninstall.ps1
  scripts/test/lint.py
Labels: :new: package

#888 :robot: Add vscode.vm
  packages/vscode.vm/tools/chocolateyinstall.ps1
  packages/vscode.vm/tools/chocolateyuninstall.ps1
  packages/vscode.vm/vscode.vm.nuspec
Labels: :new: package

#904 :robot: Add extreme_dumper.vm
  packages/extreme_dumper.vm/extreme_dumper.vm.nuspec
  packages/extreme_dumper.vm/tools/chocolateyinstall.ps1
  packages/extreme_dumper.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#906 [CI] Update packages number badge in README
  .github/workflows/sync_badge.yml
  README.md
Labels: :page_facing_up: documentation, :runner: CI

#895 Fix ArsenalImageMounter dependency
  packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
Labels: :bug: bug, :cyclone: COMMANDO-VM

#912 [CI] Use bot token for better branch protection
  .github/workflows/sync_badge.yml
Labels: :runner: CI

#915 [CI] Use dynamic badge for package number
  .github/workflows/sync_badge.yml
  README.md
Labels: :runner: CI

#855 Fix shortcuts in didier-stevens-suite.vm
  packages/didier-stevens-suite.vm/didier-stevens-suite.vm.nuspec
  packages/didier-stevens-suite.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :grey_question: discussion, :cyclone: FLARE-VM

#854 Fix shortcuts in didier-stevens-beta.vm
  packages/didier-stevens-beta.vm/didier-stevens-beta.vm.nuspec
  packages/didier-stevens-beta.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :grey_question: discussion, :cyclone: FLARE-VM

#905 [CI] Test automated new package before PR
  .github/workflows/new_package.yml
Labels: :runner: CI

#916 [CI] Use dynamic badges for daily run failures
  .github/workflows/daily.yml
  README.md
Labels: :page_facing_up: documentation, :runner: CI

#918 [arsenalimagemounter] Do not update dotnet-8
  packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
Labels: :gem: enhancement

#908 [CI] Remove "flarevm.installer.vm"
  scripts/test/lint.py
  scripts/test/test_install.ps1
Labels: :runner: CI

#924 :robot: Add regcool.vm
  packages/regcool.vm/regcool.vm.nuspec
  packages/regcool.vm/tools/chocolateyinstall.ps1
  packages/regcool.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#922 :robot: Add total-registry.vm
  packages/total-registry.vm/tools/chocolateyinstall.ps1
  packages/total-registry.vm/tools/chocolateyuninstall.ps1
  packages/total-registry.vm/total-registry.vm.nuspec
Labels: :new: package

#909 [VM-Clean-Up] Sort Desktop icons by type
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement
