Repository mandiant/VM-Packages, pull requests merged in 2024-03, with the labels that each got.

#928 [CI] Use @google.com email for bot
  .github/workflows/daily.yml
  .github/workflows/new_package.yml
  .github/workflows/update_package.yml
Labels: :runner: CI

#926 [CI] Update actions to use immutable release and non deprecated version of Node
  .github/actions/upload-logs/action.yml
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  .github/workflows/new_package.yml
  .github/workflows/sync_badge.yml
  .github/workflows/update_package.yml
Labels: :runner: CI

#858 Add better shortcut icons for .py and .bat
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#931 [installer] Fix creation of Admin Command Prompt
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#933 [installer] Fix creation of Admin Command Prompt
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#938 [pesieve] Use shortcut helper & console app
  packages/pesieve.vm/pesieve.vm.nuspec
  packages/pesieve.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#936 Package Fix: Microsoft-Windows-Terminal
  packages/microsoft-windows-terminal.vm/tools/chocolateyinstall.ps1
  packages/microsoft-windows-terminal.vm/tools/chocolateyuninstall.ps1
  packages/windows-terminal.vm/tools/chocolateyinstall.ps1
  packages/windows-terminal.vm/tools/chocolateyuninstall.ps1
  packages/windows-terminal.vm/windows-terminal.vm.nuspec
Labels: :cyclone: FLARE-VM

#871 Add powershell support in VM-Install-Shortcut
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#939 [create_package_template] Improve template
  scripts/utils/create_package_template.py
Labels: :bug: bug, :runner: CI

#944 [sysinternals.vm] Add tools to PATH & fix exception order
  packages/sysinternals.vm/sysinternals.vm.nuspec
  packages/sysinternals.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#957 New Remove-Appx-Package function
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/debloat.vm/debloat.vm.nuspec
  packages/debloat.vm/tools/win10.xml
Labels: :gem: enhancement, :cyclone: FLARE-VM, :cyclone: COMMANDO-VM

#958 Package update
  packages/event-log-explorer.vm/event-log-explorer.vm.nuspec
  packages/event-log-explorer.vm/tools/chocolateyinstall.ps1
  packages/mftecmd.vm/mftecmd.vm.nuspec
  packages/mftecmd.vm/tools/chocolateyinstall.ps1
  packages/sbecmd.vm/sbecmd.vm.nuspec
  packages/sbecmd.vm/tools/chocolateyinstall.ps1
  packages/timeline_explorer.vm/timeline_explorer.vm.nuspec
  packages/timeline_explorer.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement
