Repository mandiant/VM-Packages, pull requests merged in 2024-12, with the labels that each got.

#1186 Add Python category and unpyc3.vm
  .github/ISSUE_TEMPLATE/new_metapackage.yml
  .github/ISSUE_TEMPLATE/new_node_package.yml
  .github/ISSUE_TEMPLATE/new_package.yml
  categories.txt
  packages/unpyc3.vm/tools/chocolateyinstall.ps1
  packages/unpyc3.vm/tools/chocolateyuninstall.ps1
  packages/unpyc3.vm/unpyc3.vm.nuspec
Labels: :gem: enhancement, :new: package, :cyclone: FLARE-VM

#1169 Clarify vcbuildtools.vm dependency
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/metasploit.vm/metasploit.vm.nuspec
  packages/sysinternals.vm/sysinternals.vm.nuspec
Labels: :page_facing_up: documentation

#1170 [common] Add VM-Unzip-Recursively
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1177 Use updated ida_launcher
  packages/idafree.vm/idafree.vm.nuspec
  packages/idafree.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1179 Pin magika version to fix pip issue
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/magika.vm/magika.vm.nuspec
  packages/magika.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#1164 Set Chrome as default browser
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/googlechrome.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM

#1178 Add internet_detector scheduled task
  packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
  packages/fakenet-ng.vm/tools/default.ini
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
  packages/internet_detector.vm/tools/internet_detector.pyw
Labels: :cyclone: FLARE-VM

#1193 [ida.plugin.capa.vm] Update to version 8.0.1
  packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
  packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.capa.vm/tools/chocolateyuninstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1200 Fix RegCool Hash
  packages/regcool.vm/regcool.vm.nuspec
  packages/regcool.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1203 Update hash for event-log-explorer
  packages/event-log-explorer.vm/event-log-explorer.vm.nuspec
  packages/event-log-explorer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1206 [libraries.python3.vm] Add rpyc
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/libraries.python3.vm/tools/modules.xml
Labels: :bug: bug, :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1207 Add xrefer.vm
  packages/ida.plugin.xrefer.vm/ida.plugin.xrefer.vm.nuspec
  packages/ida.plugin.xrefer.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.xrefer.vm/tools/chocolateyuninstall.ps1
  packages/libraries-extra.python3.vm/libraries-extra.python3.vm.nuspec
Labels: :new: package, :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1209 [vcredist140] Update to version 14.42
  packages/vcredist140.vm/vcredist140.vm.nuspec
Labels: :bug: bug

#1215 Fix VM-Unzip-Recursively
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :bug: bug

#1218 [internet_detector.vm] Do not run by default
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1221 Fix Internet Detector Background/Taskbar Issues
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
  packages/internet_detector.vm/tools/internet_detector.pyw
Labels: :bug: bug, :cyclone: FLARE-VM
