Repository mandiant/VM-Packages, pull requests merged in 2024-07, with the labels that each got.

#1106 [pdbs.pdbresym.vm] Download .NET PDBs
  packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
  packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1109 Ensure strings from sysinternals is the first in PATH
  packages/sysinternals.vm/sysinternals.vm.nuspec
  packages/sysinternals.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement

#1108 Add the CFF Explorer icon to the right click & fix uninstallation
  packages/explorersuite.vm/explorersuite.vm.nuspec
  packages/explorersuite.vm/tools/chocolateyinstall.ps1
  packages/explorersuite.vm/tools/chocolateyuninstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1098 Fix missing dependency in hashdb plugin
  packages/ida.plugin.comida.vm/ida.plugin.comida.vm.nuspec
  packages/ida.plugin.dereferencing.vm/ida.plugin.dereferencing.vm.nuspec
  packages/ida.plugin.diaphora.vm/ida.plugin.diaphora.vm.nuspec
  packages/ida.plugin.flare.vm/ida.plugin.flare.vm.nuspec
  packages/ida.plugin.hashdb.vm/ida.plugin.hashdb.vm.nuspec
  packages/ida.plugin.ifl.vm/ida.plugin.ifl.vm.nuspec
  packages/ida.plugin.lighthouse.vm/ida.plugin.lighthouse.vm.nuspec
Labels: :bug: bug, :cyclone: FLARE-VM
