Repository mandiant/VM-Packages, pull requests merged in 2024-11, with the labels that each got.

#1156 Improve VM-Pip-Install & add libraries-extra.python3.vm
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
  packages/libraries-extra.python3.vm/libraries-extra.python3.vm.nuspec
  packages/libraries-extra.python3.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :new: package, :cyclone: FLARE-VM

#1157 Improve VM-Assert-Signature & restore hash installation for RegCool
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/metasploit.vm/metasploit.vm.nuspec
  packages/regcool.vm/regcool.vm.nuspec
  packages/regcool.vm/tools/chocolateyinstall.ps1
  packages/sysinternals.vm/sysinternals.vm.nuspec
Labels: :gem: enhancement

#1158 [update_packages.yml] Improve PR body
  .github/workflows/update_packages.yml
Labels: :page_facing_up: documentation, :gem: enhancement, :runner: CI

#1139 Add chrome.extensions.vm
  packages/chrome.extensions.vm/chrome.extensions.vm.nuspec
  packages/chrome.extensions.vm/tools/chocolateyinstall.ps1
  packages/chrome.extensions.vm/tools/chocolateyuninstall.ps1
  scripts/test/lint.py
Labels: :new: package, :cyclone: FLARE-VM

#1163 Fix internet_detector not installing
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM

#1161 Fix IDA Pro 9.0+ Right Click Open
  ida_launcher/ida_launcher.exe
  ida_launcher/src/ida_launcher.c
Labels: :bug: bug, :cyclone: FLARE-VM

#1160 :robot: Add recaf.vm
  packages/recaf.vm/recaf.vm.nuspec
  packages/recaf.vm/tools/chocolateyinstall.ps1
  packages/recaf.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM
