Repository mandiant/VM-Packages, pull requests merged in 2024-04, with the labels that each got.

#962 Set Windows Terminal as pinned console
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/debloat.vm/debloat.vm.nuspec
  packages/debloat.vm/tools/win10.xml
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
  packages/windows-terminal.vm/tools/chocolateyinstall.ps1
  packages/windows-terminal.vm/tools/chocolateyuninstall.ps1
  packages/windows-terminal.vm/windows-terminal.vm.nuspec
Labels: :gem: enhancement, :cyclone: FLARE-VM

#949 :robot: Add windump.vm
  packages/windump.vm/tools/chocolateyinstall.ps1
  packages/windump.vm/tools/chocolateyuninstall.ps1
  packages/windump.vm/windump.vm.nuspec
Labels: :new: package

#236 Add x64dbg DbgChild
  packages/x64dbg.dbgchild.vm/tools/chocolateyinstall.ps1
  packages/x64dbg.dbgchild.vm/tools/chocolateyuninstall.ps1
  packages/x64dbg.dbgchild.vm/x64dbg.dbgchild.vm.nuspec
  scripts/test/lint.py
Labels: :new: package, :cyclone: FLARE-VM

#968 Remove Tor Desktop Shortcut
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/tor-browser.vm/tools/chocolateyinstall.ps1
  packages/tor-browser.vm/tor-browser.vm.nuspec
Labels: :bug: bug

#935 Package proposal: magika
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/magika.vm/magika.vm.nuspec
  packages/magika.vm/tools/chocolateyinstall.ps1
  packages/magika.vm/tools/chocolateyuninstall.ps1
Labels: :gem: enhancement, :new: package, :cyclone: FLARE-VM

#920 :robot: Add 7z-nsis.vm
  packages/7z-nsis.vm/7z-nsis.vm.nuspec
  packages/7z-nsis.vm/tools/chocolateyinstall.ps1
  packages/7z-nsis.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#978 Bypass annoying chrome pop-ups
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/googlechrome.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#983 Remove Cmd Here from Registry
  packages/map.vm/map.vm.nuspec
  packages/map.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#986 Add pdbresym.vm
  packages/pdbresym.vm/pdbresym.vm.nuspec
  packages/pdbresym.vm/tools/chocolateyinstall.ps1
  packages/pdbresym.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#989 [fakenet-ng.vm] Update tool and improve code
  packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
  packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
  packages/fakenet-ng.vm/tools/chocolateyuninstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#990 [script/CI] Remove GITHUB_REPO
  .github/ISSUE_TEMPLATE/new_package.yml
  scripts/utils/create_package_template.py
Labels: :runner: CI

#596 :robot: Add egress-assess.vm
  packages/egress-assess.vm/egress-assess.vm.nuspec
  packages/egress-assess.vm/tools/chocolateyinstall.ps1
  packages/egress-assess.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: COMMANDO-VM

#595 :robot: Add internal-monologue.vm
  packages/internal-monologue.vm/internal-monologue.vm.nuspec
  packages/internal-monologue.vm/tools/chocolateyinstall.ps1
  packages/internal-monologue.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: COMMANDO-VM

#995 [libraries.python3.vm] Fix dependency version
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
Labels: :bug: bug

#998 fix param bug with vm-uninstall-with-uninstaller
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/map.vm/map.vm.nuspec
  packages/map.vm/tools/chocolateyuninstall.ps1
Labels: :bug: bug

#1003 [pdbs.pdbresym.vm] Set _NT_SYMBOL_PATH
  packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
  packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1000 Add helper function for Node tools
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/malware-jail.vm/malware-jail.vm.nuspec
  packages/malware-jail.vm/tools/chocolateyinstall.ps1
  packages/pkg-unpacker.vm/pkg-unpacker.vm.nuspec
  packages/pkg-unpacker.vm/tools/chocolateyinstall.ps1
  scripts/test/lint.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#741 Update Resource Hacker
  packages/resourcehacker.vm/resourcehacker.vm.nuspec
  packages/resourcehacker.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM, :cyclone: COMMANDO-VM

#1009 Force same icon layout when sorting
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1013 Add IDA plugins helper functions & templates to script
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
  packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.capa.vm/tools/chocolateyuninstall.ps1
  packages/ida.plugin.sigmaker.vm/ida.plugin.sigmaker.vm.nuspec
  packages/ida.plugin.sigmaker.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.sigmaker.vm/tools/chocolateyuninstall.ps1
  scripts/test/lint.py
  scripts/utils/create_package_template.py
Labels: :grey_question: discussion, :new: package, :cyclone: FLARE-VM

#1006 [fiddler.vm] Follow metapackage documentation
  packages/fiddler.vm/fiddler.vm.nuspec
  packages/fiddler.vm/tools/chocolateyinstall.ps1
  packages/fiddler.vm/tools/chocolateyuninstall.ps1
Labels: :bug: bug, :cyclone: COMMANDO-VM

#1014 Install flare-capa in ida.plugin.capa.vm
  packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
  packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/libraries.python3.vm/tools/modules.xml
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1020 Add ZIP support in VM-Install-IDA-Plugin & Add ida.plugin.dereferencing.vm
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/ida.plugin.dereferencing.vm/ida.plugin.dereferencing.vm.nuspec
  packages/ida.plugin.dereferencing.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.dereferencing.vm/tools/chocolateyuninstall.ps1
  scripts/utils/create_package_template.py
Labels: :gem: enhancement, :new: package, :cyclone: FLARE-VM
