Repository mandiant/VM-Packages, pull requests merged in 2024-08, with the labels that each got.

#1115 Added static download link for NetworkMiner 2.9
  packages/networkminer.vm/networkminer.vm.nuspec
  packages/networkminer.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM

#1113 [libraries.python3.vm] Add pycryptodomex library
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/libraries.python3.vm/tools/modules.xml
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1118 [pdbs.pdbresym.vm] Download x32 and driver PDBs
  packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
  packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1119 [common] Add VM-Set-Legal-Notice helper function
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1120 [microsoft-office.vm] Add package
  packages/microsoft-office.vm/microsoft-office.vm.nuspec
  packages/microsoft-office.vm/tools/chocolateyinstall.ps1
  scripts/test/lint.py
Labels: :new: package, :cyclone: FLARE-VM

#1122 Fix daily test
  .github/workflows/daily.yml
Labels: :bug: bug, :runner: CI

#1123 Fix ZimmermanTools Install
  packages/amcacheparser.vm/amcacheparser.vm.nuspec
  packages/amcacheparser.vm/tools/chocolateyinstall.ps1
  packages/appcompatcacheparser.vm/appcompatcacheparser.vm.nuspec
  packages/appcompatcacheparser.vm/tools/chocolateyinstall.ps1
  packages/bstrings.vm/bstrings.vm.nuspec
  packages/bstrings.vm/tools/chocolateyinstall.ps1
  packages/evtxecmd.vm/evtxecmd.vm.nuspec
  packages/evtxecmd.vm/tools/chocolateyinstall.ps1
  packages/ezviewer.vm/ezviewer.vm.nuspec
  packages/ezviewer.vm/tools/chocolateyinstall.ps1
  packages/hasher.vm/hasher.vm.nuspec
  packages/hasher.vm/tools/chocolateyinstall.ps1
  packages/jlecmd.vm/jlecmd.vm.nuspec
  packages/jlecmd.vm/tools/chocolateyinstall.ps1
  packages/jumplist_explorer.vm/jumplist_explorer.vm.nuspec
  packages/jumplist_explorer.vm/tools/chocolateyinstall.ps1
  packages/lecmd.vm/lecmd.vm.nuspec
  packages/lecmd.vm/tools/chocolateyinstall.ps1
  packages/mft_explorer.vm/mft_explorer.vm.nuspec
  packages/mft_explorer.vm/tools/chocolateyinstall.ps1
  packages/mftecmd.vm/mftecmd.vm.nuspec
  packages/mftecmd.vm/tools/chocolateyinstall.ps1
  packages/pecmd.vm/pecmd.vm.nuspec
  packages/pecmd.vm/tools/chocolateyinstall.ps1
  packages/rbcmd.vm/rbcmd.vm.nuspec
  packages/rbcmd.vm/tools/chocolateyinstall.ps1
  packages/recentfilecacheparser.vm/recentfilecacheparser.vm.nuspec
  packages/recentfilecacheparser.vm/tools/chocolateyinstall.ps1
  packages/recmd.vm/recmd.vm.nuspec
  packages/recmd.vm/tools/chocolateyinstall.ps1
  packages/registry_explorer.vm/registry_explorer.vm.nuspec
  packages/registry_explorer.vm/tools/chocolateyinstall.ps1
  packages/rla.vm/rla.vm.nuspec
  packages/rla.vm/tools/chocolateyinstall.ps1
  packages/sbecmd.vm/sbecmd.vm.nuspec
  packages/sbecmd.vm/tools/chocolateyinstall.ps1
  packages/sdb_explorer.vm/sdb_explorer.vm.nuspec
  packages/sdb_explorer.vm/tools/chocolateyinstall.ps1
  packages/shellbags_explorer.vm/shellbags_explorer.vm.nuspec
  packages/shellbags_explorer.vm/tools/chocolateyinstall.ps1
  packages/sqlecmd.vm/sqlecmd.vm.nuspec
  packages/sqlecmd.vm/tools/chocolateyinstall.ps1
  packages/srumecmd.vm/srumecmd.vm.nuspec
  packages/srumecmd.vm/tools/chocolateyinstall.ps1
  packages/sumecmd.vm/sumecmd.vm.nuspec
  packages/sumecmd.vm/tools/chocolateyinstall.ps1
  packages/timeline_explorer.vm/timeline_explorer.vm.nuspec
  packages/timeline_explorer.vm/tools/chocolateyinstall.ps1
  packages/vscmount.vm/tools/chocolateyinstall.ps1
  packages/vscmount.vm/vscmount.vm.nuspec
  packages/wxtcmd.vm/tools/chocolateyinstall.ps1
  packages/wxtcmd.vm/wxtcmd.vm.nuspec
Labels: :bug: bug, :cyclone: FLARE-VM

#1126 [daily] Increase timeout again
  .github/workflows/daily.yml
Labels: :gem: enhancement, :runner: CI
