Repository mandiant/VM-Packages, pull requests merged in 2024-01, with the labels that each got.

#804 uniextract: Change category to Packers
  packages/uniextract2.vm/tools/chocolateyinstall.ps1
  packages/uniextract2.vm/tools/chocolateyuninstall.ps1
  packages/uniextract2.vm/uniextract2.vm.nuspec
Labels: :gem: enhancement

#816 Improve VM-Clean-Up
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#817 Improve Clean Up
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :bug: bug

#803 Improve 7zip-15-05.vm
  packages/7zip-15-05.vm/7zip-15-05.vm.nuspec
  packages/7zip-15-05.vm/tools/chocolateyinstall.ps1
  packages/7zip-15-05.vm/tools/chocolateyuninstall.ps1
  scripts/test/lint.py
Labels: :gem: enhancement

#835 :robot: Add blobrunner64.vm
  packages/blobrunner64.vm/blobrunner64.vm.nuspec
  packages/blobrunner64.vm/tools/chocolateyinstall.ps1
  packages/blobrunner64.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#836 :robot: Add blobrunner.vm
  packages/blobrunner.vm/blobrunner.vm.nuspec
  packages/blobrunner.vm/tools/chocolateyinstall.ps1
  packages/blobrunner.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM

#827 Fix sysinternals (and avoid that it breaks again!)
  packages/sysinternals.vm/sysinternals.vm.nuspec
  packages/sysinternals.vm/tools/chocolateyinstall.ps1
  packages/sysinternals.vm/tools/chocolateyuninstall.ps1
Labels: :bug: bug, :gem: enhancement

#832 Fix broken rubeus by using a URL whose hash doesn't change
  packages/rubeus.vm/rubeus.vm.nuspec
  packages/rubeus.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: COMMANDO-VM

#833 Fix broken situational-awareness-bof by using a URL whose hash doesn't change
  packages/situational-awareness-bof.vm/situational-awareness-bof.vm.nuspec
  packages/situational-awareness-bof.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: COMMANDO-VM

#829 Fix gowitness by updating dependency
  packages/gowitness.vm/gowitness.vm.nuspec
Labels: :bug: bug, :cyclone: COMMANDO-VM

#879 [libraries.python3] Install lznt1 Python library
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/libraries.python3.vm/tools/modules.xml
Labels: :gem: enhancement
