Repository mandiant/VM-Packages, pull requests merged in 2025-01, with the labels that each got.

#1220 [npcap.vm] Fix npcap never finishing, blocking FLARE-VM installation
  packages/npcap.vm/npcap.vm.nuspec
  packages/npcap.vm/tools/chocolateyinstall.ps1
  packages/npcap.vm/tools/install.ahk
Labels: :bug: bug, :cyclone: FLARE-VM

#1197 Add GitHub Action to Create Package Wiki
  .github/workflows/generate_package_wiki.yml
  scripts/utils/generate_package_wiki.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1227 Remove double console when opening fakenet
  packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
  packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1175 [new_package.yml] Improve PR description
  .github/workflows/new_package.yml
Labels: :runner: CI

#1237 :robot: Add ida.plugin.xray.vm
  packages/ida.plugin.xray.vm/ida.plugin.xray.vm.nuspec
  packages/ida.plugin.xray.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.xray.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#1234 Add pycdc.vm and pycdas.vm
  packages/pycdas.vm/pycdas.vm.nuspec
  packages/pycdas.vm/tools/chocolateyinstall.ps1
  packages/pycdas.vm/tools/chocolateyuninstall.ps1
  packages/pycdc.vm/pycdc.vm.nuspec
  packages/pycdc.vm/tools/chocolateyinstall.ps1
  packages/pycdc.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#1236 [hashmyfiles.vm] Add config file
  packages/hashmyfiles.vm/hashmyfiles.vm.nuspec
  packages/hashmyfiles.vm/tools/chocolateyinstall.ps1
  packages/hashmyfiles.vm/tools/hashmyfiles.cfg
Labels: :gem: enhancement

#1238 Improve license & copyright & documentation
  CONTRIBUTING.md
  LICENSE.txt
  NOTICE.txt
  README.md
  scripts/test/lint.py
Labels: :page_facing_up: documentation

#1250 [visualstudio.vm] Increase execution timeout
  packages/visualstudio.vm/tools/chocolateyinstall.ps1
  packages/visualstudio.vm/visualstudio.vm.nuspec
Labels: :gem: enhancement

#1246 :robot: Add rat-king-parser.vm
  packages/rat-king-parser.vm/rat-king-parser.vm.nuspec
  packages/rat-king-parser.vm/tools/chocolateyinstall.ps1
  packages/rat-king-parser.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#1248 :robot: Add uncompyle6.vm
  packages/uncompyle6.vm/tools/chocolateyinstall.ps1
  packages/uncompyle6.vm/tools/chocolateyuninstall.ps1
  packages/uncompyle6.vm/uncompyle6.vm.nuspec
Labels: :new: package

#1249 [common.vm] Improve VM-Write-Log
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement

#1243 Add idapro.vm
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/cyberchef.vm/cyberchef.vm.nuspec
  packages/cyberchef.vm/tools/chocolateyinstall.ps1
  packages/explorersuite.vm/explorersuite.vm.nuspec
  packages/explorersuite.vm/tools/chocolateyinstall.ps1
  packages/explorersuite.vm/tools/chocolateyuninstall.ps1
  packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
  packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
  packages/fakenet-ng.vm/tools/chocolateyuninstall.ps1
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/googlechrome.vm/tools/chocolateyinstall.ps1
  packages/idafree.vm/idafree.vm.nuspec
  packages/idafree.vm/tools/chocolateyinstall.ps1
  packages/idafree.vm/tools/chocolateyuninstall.ps1
  packages/idapro.vm/idapro.vm.nuspec
  packages/idapro.vm/tools/chocolateyinstall.ps1
  packages/idapro.vm/tools/chocolateyuninstall.ps1
  packages/notepadplusplus.vm/notepadplusplus.vm.nuspec
  packages/notepadplusplus.vm/tools/chocolateyinstall.ps1
  packages/sysinternals.vm/sysinternals.vm.nuspec
  packages/sysinternals.vm/tools/chocolateyinstall.ps1
  packages/sysinternals.vm/tools/chocolateyuninstall.ps1
  packages/visualstudio.vm/tools/chocolateyinstall.ps1
  packages/visualstudio.vm/tools/chocolateyuninstall.ps1
  packages/visualstudio.vm/visualstudio.vm.nuspec
  packages/windows-terminal.vm/tools/chocolateyinstall.ps1
  packages/windows-terminal.vm/windows-terminal.vm.nuspec
  scripts/test/test_install.ps1
Labels: :new: package, :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1253 Update ilspy.vm & add dotnet-8.vm
  packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
  packages/dotnet-8.vm/dotnet-8.vm.nuspec
  packages/ilspy.vm/ilspy.vm.nuspec
Labels: :gem: enhancement, :new: package

#1259 Add ida.plugin.hrtng.vm
  packages/ida.plugin.hrtng.vm/ida.plugin.hrtng.vm.nuspec
  packages/ida.plugin.hrtng.vm/tools/chocolateyinstall.ps1
  packages/ida.plugin.hrtng.vm/tools/chocolateyuninstall.ps1
Labels: :new: package, :cyclone: FLARE-VM, :curly_haired_woman: IDA
