Repository mandiant/VM-Packages, pull requests merged in 2025-04, with the labels that each got.

#1333 [map.vm] Update to latest version
  packages/map.vm/map.vm.nuspec
  packages/map.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM

#1353 Check for chocolateyinstall.ps1 before updating the packages
  scripts/utils/update_package.py
Labels: :bug: bug

#1357 Fix net-reactor-slayer.vm shortcut working directory
  packages/net-reactor-slayer.vm/net-reactor-slayer.vm.nuspec
  packages/net-reactor-slayer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#1352 Fix the missing registry key check at googlechrome.vm
  packages/googlechrome.vm/googlechrome.vm.nuspec
  packages/googlechrome.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#1360 Support installing custom locales
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1356 Add new PIP package keystone-engine
  packages/keystone.vm/keystone.vm.nuspec
  packages/keystone.vm/tools/chocolateyinstall.ps1
  packages/keystone.vm/tools/chocolateyuninstall.ps1
  scripts/test/lint.py
Labels: :new: package

#1364 [CI] Update Ubuntu version in action
  .github/workflows/sync_badge.yml
Labels: :bug: bug, :runner: CI

#1350 Add broken hash fix automation
  .github/workflows/update_packages.yml
  packages/mftecmd.vm/mftecmd.vm.nuspec
  scripts/utils/update_package.py
Labels: :gem: enhancement, :runner: CI

#1261 Use ICMP instead of HTTP for testing the connection
  packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
  packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
  packages/fakenet-ng.vm/tools/default.ini
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
  packages/internet_detector.vm/tools/chocolateyuninstall.ps1
  packages/internet_detector.vm/tools/internet_detector.pyw
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1343 Add package GoStringUngarbler
  packages/gostringungarbler.vm/gostringungarbler.vm.nuspec
  packages/gostringungarbler.vm/tools/chocolateyinstall.ps1
  packages/gostringungarbler.vm/tools/chocolateyuninstall.ps1
Labels: :new: package

#1359 Start the internet detector at user logon immediately
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
  packages/internet_detector.vm/tools/chocolateyuninstall.ps1
Labels: :gem: enhancement

#1370 Add comment to VM-Install-Node-Tool
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :page_facing_up: documentation

#1377 Fix the uninstallation of internet_detector.vm
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyuninstall.ps1
Labels: :bug: bug

#1373 Improve shortcut creation in visualstudio.vm and microsoft-office.vm
  packages/microsoft-office.vm/microsoft-office.vm.nuspec
  packages/microsoft-office.vm/tools/chocolateyinstall.ps1
  packages/visualstudio.vm/tools/chocolateyinstall.ps1
  packages/visualstudio.vm/visualstudio.vm.nuspec
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1354 Update the version of pefile
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/chocolateyinstall.ps1
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/libraries.python3.vm/tools/modules.xml
Labels: :gem: enhancement

#1374 [debloat.vm] Disable Office key
  packages/debloat.vm/debloat.vm.nuspec
  packages/debloat.vm/tools/win10.xml
Labels: :gem: enhancement

#1384 [garbageman] Fix dependency
  packages/garbageman.vm/garbageman.vm.nuspec
Labels: :bug: bug, :cyclone: FLARE-VM

#1387 [internet_detector] Fix: Install dependency
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/libraries.python3.vm/tools/modules.xml
Labels: :bug: bug, :cyclone: FLARE-VM

#1355 Fix links in the metadata package template
  .github/ISSUE_TEMPLATE/new_IDA_plugin.yml
  .github/ISSUE_TEMPLATE/new_metapackage.yml
  .github/ISSUE_TEMPLATE/new_node_package.yml
  .github/ISSUE_TEMPLATE/new_package.yml
  .github/ISSUE_TEMPLATE/new_python_tool_pip.yml
Labels: :page_facing_up: documentation

#1379 Re-try package installation on failure
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1394 [regcool.vm] Use 0.0.0.YYYYDDMM version format
  packages/regcool.vm/regcool.vm.nuspec
Labels: :gem: enhancement, :runner: CI
