Repository mandiant/VM-Packages, pull requests merged in 2025-07, with the labels that each got.

#1401 Add size & time info to descriptions
  packages/010editor.vm/010editor.vm.nuspec
  packages/pdbresym.vm/pdbresym.vm.nuspec
  packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
  packages/visualstudio.vm/visualstudio.vm.nuspec
Labels: :page_facing_up: documentation

#1431 Update IDA Capa Plugin
  packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
  packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
Labels: :cyclone: FLARE-VM, :curly_haired_woman: IDA

#1444 [CI] Fix daily
  .github/workflows/daily.yml
Labels: :bug: bug, :runner: CI

#1443 Improve Packages Wiki page
  README.md
  scripts/utils/generate_package_wiki.py
Labels: :page_facing_up: documentation, :runner: CI

#1437 [CI] Test that the package version is increased
  scripts/test/lint.py
Labels: :gem: enhancement, :runner: CI

#1446 [doc (nuspecs)] Improve documentation of several tools
  packages/binaryninja.vm/binaryninja.vm.nuspec
  packages/burp-free.vm/burp-free.vm.nuspec
  packages/covenant.vm/covenant.vm.nuspec
  packages/hxd.vm/hxd.vm.nuspec
  packages/ifpstools.vm/ifpstools.vm.nuspec
  packages/imhex.vm/imhex.vm.nuspec
  packages/innoextract.vm/innoextract.vm.nuspec
  packages/innounp.vm/innounp.vm.nuspec
  packages/isd.vm/isd.vm.nuspec
  packages/juicypotato.vm/juicypotato.vm.nuspec
  packages/libraries.python3.vm/libraries.python3.vm.nuspec
  packages/metasploit.vm/metasploit.vm.nuspec
  packages/pycdas.vm/pycdas.vm.nuspec
  packages/pycdc.vm/pycdc.vm.nuspec
  packages/python3.vm/python3.vm.nuspec
  packages/uncompyle6.vm/uncompyle6.vm.nuspec
  packages/unpyc3.vm/unpyc3.vm.nuspec
Labels: :page_facing_up: documentation

#1450 [CI: daily] Reduce tries to 3
  .github/workflows/daily.yml
Labels: :bug: bug, :runner: CI

#1417 WxTCmd updated hash
  packages/wxtcmd.vm/tools/chocolateyinstall.ps1
  packages/wxtcmd.vm/wxtcmd.vm.nuspec
Labels: :bug: bug

#1439 Fix(ci): Ensure clean state between package tests
  .github/workflows/update_packages.yml
Labels: :runner: CI, :cyclone: FLARE-VM

#1452 Enhance update_package.py
  scripts/utils/update_package.py
Labels: :gem: enhancement, :runner: CI

#1459 [CI] Fix CI status badge in README
  README.md
Labels: :bug: bug, :page_facing_up: documentation, :runner: CI

#1460 [CI] Fix update_packages.yml and improve its log output
  .github/workflows/update_packages.yml
Labels: :bug: bug, :runner: CI

#1463 Fix Win11 internet by moving DNSCache change to only Win10
  packages/debloat.vm/debloat.vm.nuspec
  packages/debloat.vm/tools/win10.xml
Labels: :bug: bug, :cyclone: FLARE-VM

#1469 [CI] Fix Version check in linter
  scripts/test/lint.py
Labels: :bug: bug, :runner: CI

#1475 Fix the SHA256 hash mismatches
  packages/bstrings.vm/bstrings.vm.nuspec
  packages/bstrings.vm/tools/chocolateyinstall.ps1
  packages/timeline_explorer.vm/timeline_explorer.vm.nuspec
  packages/timeline_explorer.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug

#1461 [doc] Add installer type to new_package.yml
  .github/ISSUE_TEMPLATE/new_package.yml
Labels: :page_facing_up: documentation

#1462 Fix: Resolve 'ttd.vm' and 'windbg.vm' installation issues on Windows 11
  packages/debloat.vm/debloat.vm.nuspec
  packages/debloat.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM, :window: Windows11
