Repository mandiant/VM-Packages, pull requests merged in 2025-08, with the labels that each got.

#1488 [sysinternals.vm] Prevent duplication in taskbar
  packages/sysinternals.vm/sysinternals.vm.nuspec
  packages/sysinternals.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1489 Fix internet detector taskbar color refreshing
  packages/internet_detector.vm/internet_detector.vm.nuspec
  packages/internet_detector.vm/tools/internet_detector.pyw
Labels: :bug: bug, :cyclone: FLARE-VM

#1490 Revert "[VM-Install-Shortcut] Enhance code and ensure shortcut is created "
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
Labels: :gem: enhancement

#982 De-ConsoleApp Windump
  packages/windump.vm/tools/chocolateyinstall.ps1
  packages/windump.vm/windump.vm.nuspec
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1484 Remove 'takes long to install' from 010 description
  packages/010editor.vm/010editor.vm.nuspec
Labels: :gem: enhancement, :cyclone: FLARE-VM

#1468 [CI: update_package.py] Handle requests errors
  scripts/utils/update_package.py
Labels: :bug: bug, :runner: CI
