Repository mandiant/VM-Packages, pull requests merged in 2025-02, with the labels that each got.

#1199 Use SigCheck w/ Zimmerman Tools
  packages/common.vm/common.vm.nuspec
  packages/common.vm/tools/vm.common/vm.common.psm1
  packages/evtxecmd.vm/evtxecmd.vm.nuspec
  packages/evtxecmd.vm/tools/chocolateyinstall.ps1
  packages/pecmd.vm/pecmd.vm.nuspec
  packages/pecmd.vm/tools/chocolateyinstall.ps1
  packages/recmd.vm/recmd.vm.nuspec
  packages/recmd.vm/tools/chocolateyinstall.ps1
  packages/registry_explorer.vm/registry_explorer.vm.nuspec
  packages/registry_explorer.vm/tools/chocolateyinstall.ps1
  packages/rla.vm/rla.vm.nuspec
  packages/rla.vm/tools/chocolateyinstall.ps1
  packages/sqlecmd.vm/sqlecmd.vm.nuspec
  packages/sqlecmd.vm/tools/chocolateyinstall.ps1
Labels: :bug: bug, :cyclone: FLARE-VM

#1265 [microsoft-office.vm] Improve installation params & add verification + shortcuts
  packages/microsoft-office.vm/microsoft-office.vm.nuspec
  packages/microsoft-office.vm/tools/chocolateyinstall.ps1
  scripts/test/lint.py
Labels: :gem: enhancement

#1269 Fix hash in vb-decompiler-lite.vm
  packages/vb-decompiler-lite.vm/tools/chocolateyinstall.ps1
  packages/vb-decompiler-lite.vm/vb-decompiler-lite.vm.nuspec
Labels: :bug: bug, :cyclone: FLARE-VM

#1274 [installer.vm] Always create failed_packages.txt
  packages/installer.vm/installer.vm.nuspec
  packages/installer.vm/tools/chocolateyinstall.ps1
Labels: :gem: enhancement

#1273 URL package proposal: invokethehash.vm #1241
  packages/invoke-thehash.vm/invoke-thehash.vm.nuspec
  packages/invoke-thehash.vm/tools/chocolateyinstall.ps1
  packages/invoke-thehash.vm/tools/chocolateyuninstall.ps1
Labels: :new: package
